name: deploy brush-question-frontend
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "brush-question-frontend/**"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.20.2"
      - uses: pnpm/action-setup@v3.0.0
        name: Install pnpm dependencies
        with:
          version: 8.8.0
          run_install: true
      - name: Run build task
        run: pnpm build:f
      - name: Deploy to Server html
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: brush-question-frontend/dist/
          REMOTE_HOST: "182.92.222.231"
          REMOTE_USER: root
          TARGET: /home/brush-question/brush-question-frontend
      - name: Deploy to Server nginx config
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: brush-question-frontend/nginx/
          REMOTE_HOST: "182.92.222.231"
          REMOTE_USER: root
          TARGET: /home/brush-question/nginx
